#LE INDICAMOS UN PUERTO ALEATORIO DISPONIBLE
server:
  port: 8080

#REGISTRAMOS ESTE SERVICIO EN EUREKA
eureka:
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     default-zone: http://localhost:8761/eureka
   instance:
     hostname: localhost

#INDICAMOS LA CONFIGURACIÓN PARA EL GATEWAY
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes: 
        - id: usuario-service
          uri: lb://usuario-service 
          predicates: 
            - Path=/api/usuarios/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: carro-service
          uri: lb://carro-service 
          predicates: 
            - Path=/api/carro/**      
        - id: moto-service
          uri: lb://moto-service 
          predicates: 
            - Path=/api/moto/**            
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9000/auth/realms/tutorial-realm/protocol/openid-connect/auth 
            userinfo-uri: http://localhost:9000/auth/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9000/auth/realms/tutorial-realm/protocol/openid-connect/token
        registration:
          tutorial-client:
            provider: keycloak
            client-id: tutorial-client
            client-secret: btEPzDTnZatWRiF3Acg9fkoTxnJLwRgS
            authorization-grant-type: authorization_code
            redirect-uri: "${baseUrl}/login/oauth2/code/tutorial-client"